OEP for frontend dependency upgrade
openedx/open-edx-proposals pull request #513
Opened 2023-08-23 07:16 UTC by abdullahwaheed

2023-08-23 17:52 UTC, feanil commented
This is great documentation, I think 2 things need to change: 

1. Make this an ADR on the Frontend Technology Standard OEP(OEP-11)  See https://github.com/openedx/open-edx-proposals/tree/master/oeps/best-practices/oep-0011/decisions for examples.

2. This should cross link to https://docs.openedx.org/en/latest/developers/how-tos/enable-javascript-upgrade-automation.html  and that how-to should be updated so that the info there matches the content here.  I think the mechanics and sample config can live in the how-to and what we need here is just the decision that we want to automate this and what tool to use.

2023-08-24 18:48 UTC, arbrandes requested changes
Thanks for this!  This is exactly the kind of decision we should document.

Aside from nit-picking a couple of typos (sorry, I know it's a draft, but can't help myself), I very much like the idea of documenting this.  Like Feanil, though, I think this should go in as an ADR to OEP-11.  I also support his other suggestions.

2023-08-24 18:48 UTC, arbrandes commented on oeps/best-practices/oep-0065-bp-frontend-dependencies.rst
> +Proposes best practices for maintaining dependencies on Javscript repositories of Open edX
```suggestion
Proposes best practices for maintaining dependencies on Javascript repositories of Open edX
```

2023-08-24 18:48 UTC, arbrandes commented on oeps/best-practices/oep-0065-bp-frontend-dependencies.rst
> +Openedx mico-frontends(MFEs) use javascript. We maintain these repositoriesusing  To upgrade its dependencies through package.json, we can either use `^` or `~` operators to automatically upgrade maj
```suggestion
Openedx micro-frontends(MFEs) use javascript.  We maintain these repositories using Webpack.  To upgrade its dependencies through package.json, we can either use `^` or `~` operators to automatically upgrade major and patch versions respectively. 
```

2023-08-24 18:48 UTC, arbrandes commented on oeps/best-practices/oep-0065-bp-frontend-dependencies.rst
> +We can configure Renovate Bot in our repositories by introducing `renovate.json` file. Here are some best practices we can follow to
```suggestion
We can configure Renovate Bot in our repositories by introducing `renovate.json` file. Here are some best practices on how to configure it.
```

2023-08-24 18:48 UTC, arbrandes commented on oeps/best-practices/oep-0065-bp-frontend-dependencies.rst
> +        "matchPackagePatterns": ["@edx"],
Soon we'll also have "`@openedx`", so I figure we might as well add it to the list!

2023-08-24 18:48 UTC, arbrandes commented on oeps/best-practices/oep-0065-bp-frontend-dependencies.rst
> +We can also set the automerge rules to be satisfy.
```suggestion
We can also set the automerge rules to be satisfied. 
```

2023-09-05 19:37 UTC, arbrandes requested changes
I still think that the proposed text in OEP-0066 should live entirely in the renovate ADR.

(The fact that previous OEP-11 ADRs don't contain a lot of text is only because they were moved out from the OEP and there wasn't a lot of detail to port over.)

2023-09-05 19:37 UTC, arbrandes commented on oeps/best-practices/oep-0066-bp-frontend-dependencies.rst
> +Open edX micro-frontends(MFEs) use javascript. We maintain these repositories using  To upgrade its dependencies through package.json, we can either use `^` or `~` operators to automatically upgrade
Using...?

2023-09-05 19:37 UTC, arbrandes commented on oeps/best-practices/oep-0011/decisions/0007-renovate.rst
> +To keep the micro-frontends(MFEs) of Open edX up-to-date, use some tool to autoamte the process.
```suggestion
To keep the micro-frontends(MFEs) of Open edX up-to-date, use some tool to automate the process.
```

2023-10-19 14:28 UTC, sarina commented on oeps/best-practices/oep-0011/decisions/0007-renovate.rst
> +To keep the micro-frontends(MFEs) of Open edX up-to-date, use some tool to autoamte the process.
```suggestion
To keep the micro-frontends(MFEs) of the Open edX codebase up-to-date, use some tool to automate the process.
```

2023-10-19 14:28 UTC, sarina commented on oeps/best-practices/oep-0066-bp-frontend-dependencies.rst
> +Proposes best practices for maintaining dependencies on Javascript repositories of Open edX
```suggestion
Proposes best practices for maintaining dependencies on Javascript repositories of the Open edX codebase.
```

2023-10-19 14:28 UTC, sarina commented on oeps/best-practices/oep-0066-bp-frontend-dependencies.rst
> +Here are the advantages of using renovate bot:
Above you say that this document "Proposes best practices for maintaining dependencies on Javascript repositories", yet this section just explains what options are available. Do we want to actually suggest certain values or value ranges as best practices? For example, should renovate run weekly? Monthly? (I don't know if it's appropriate to suggest values, but wanted to flag it)

2024-05-17 01:34 UTC, sarina commented
Hi @abdullahwaheed - is there continued energy to keep movement on this OEP?

2024-05-30 08:19 UTC, closed without merging